-- EXEMPLO – FUNÇÕES RTRIM(), LTRIM() E TRIM()
SELECT F.NM_FUNCIONARIO                ,       
       LTRIM(F.NM_FUNCIONARIO, 'A')    ,       
       RTRIM(F.NM_FUNCIONARIO, 'O')    ,             
       TRIM('A' FROM F.NM_FUNCIONARIO)     
  FROM T_SIP_FUNCIONARIO F;

-- EXEMPLO – FUNÇÕES NVL() e NVL2()
SELECT F.DT_NASCIMENTO                   ,
       NVL(F.DT_NASCIMENTO,'01/01/1900') ,
       NVL2(F.DT_NASCIMENTO,SYSDATE,'01/01/1900')       
  FROM T_SIP_FUNCIONARIO F;

-- EXEMPLO – FUNÇÃO REPLACE()
SELECT F.NM_FUNCIONARIO                ,
       REPLACE(F.NM_FUNCIONARIO,'A','*')
  FROM T_SIP_FUNCIONARIO F;
  
  -- EXEMPLO – FUNÇÃO SUBSTR()
SELECT F.NM_FUNCIONARIO                ,
       SUBSTR(F.NM_FUNCIONARIO,3)      ,
       SUBSTR(F.NM_FUNCIONARIO,3, 5)      
  FROM T_SIP_FUNCIONARIO F;

--FUNÇÕES NUMÉRICAS

-- EXEMPLO – FUNÇÕES NUMÉRICAS
SELECT F.VL_SALARIO_MENSAL          ,
       ROUND(F.VL_SALARIO_MENSAL)    ,
       ROUND(F.VL_SALARIO_MENSAL,1)  ,
       TRUNC(F.VL_SALARIO_MENSAL)    ,
       TRUNC(F.VL_SALARIO_MENSAL,1)  ,
       MOD(F.VL_SALARIO_MENSAL,3)    ,
       ABS(F.VL_SALARIO_MENSAL)      ,
       SQRT(F.VL_SALARIO_MENSAL)
      FROM T_SIP_FUNCIONARIO F;

--FUNÇÕES DE CONVERSÃO

-- EXEMPLO – FUNÇÕES DE CONVERSÃO – TO_CHAR()
SELECT F.VL_SALARIO_MENSAL ,
       TO_CHAR(F.VL_SALARIO_MENSAL, 'L9999999.99') "SIMBOLO MOEDA LOCAL" ,
       TO_CHAR(F.VL_SALARIO_MENSAL, 'C99,999.99') "SIMBOLO MOEDA ISO" ,
       TO_CHAR(F.VL_SALARIO_MENSAL, '99,999.99')  ,
       F.NR_MATRICULA ,
       TO_CHAR(F.NR_MATRICULA, '0099999')       
  FROM T_SIP_FUNCIONARIO F;

-- EXEMPLO – FUNÇÕES DE CONVERSÃO – TO_NUMBER()
SELECT TO_NUMBER('103')      ,
       TO_NUMBER('103') + 30 ,
       TO_NUMBER('-$12,345.99','$99,999.99')
  FROM DUAL;

-- EXEMPLO – FUNÇÕES DE CONVERSÃO – TO_DATE()
SELECT F.DT_ADMISSAO ,
       TO_DATE(F.DT_ADMISSAO,'DD/MM/YYYY')  
  FROM T_SIP_FUNCIONARIO F;

-- EXEMPLO – FUNÇÕES DE CONVERSÃO – CAST()
-- CONVERTER VALORES DE COLUNA DE UM TIPO PARA OUTRO
SELECT 
       CAST ( F.VL_SALARIO_MENSAL AS VARCHAR2(10) ) ,
       CAST ( F.VL_SALARIO_MENSAL + 1000 AS NUMBER (8,2) )
  FROM T_SIP_FUNCIONARIO F;

-- EXEMPLO – SYSDATE
SELECT SYSDATE FROM DUAL;

-- EXEMPLO – FUNÇÕES DE DATA – ADD_MONTHS()
SELECT SYSDATE                 "DATA ATUAL"  ,
       ADD_MONTHS(SYSDATE, 1)  "PRÓXIMO MÊS" ,
       ADD_MONTHS(SYSDATE, -1) "MÊS ANTERIOR"
  FROM DUAL;

-- EXEMPLO – FUNÇÕES DE DATA – LAST_DAY()
SELECT SYSDATE "DATA ATUAL" ,
       LAST_DAY(SYSDATE) "DATA COM ÚLTIMO DIA DO MÊS"
  FROM DUAL;

-- EXEMPLO – FUNÇÕES DE DATA – MONTHS_BETWEEN()
SELECT DT_ADMISSAO ,
       SYSDATE     , 
       MONTHS_BETWEEN(SYSDATE, DT_ADMISSAO) ,
       TRUNC(MONTHS_BETWEEN(SYSDATE, DT_ADMISSAO)) || ' MESES'
  FROM T_SIP_FUNCIONARIO;

