--Os scripts abaixo são as respostas para as letras do primeiro desafio da fase (comandos DML), tópico 1.3

-- Resposta do Comando SQL item A)

SELECT CAT.CD_CATEGORIA, CAT.DS_CATEGORIA, PROD.CD_PRODUTO, PROD.DS_PRODUTO, PROD.VL_UNITARIO,PROD.TP_EMBALAGEM, PROD.VL_PERC_LUCRO
    FROM MC_CATEGORIA_PROD CAT LEFT OUTER JOIN MC_PRODUTO PROD
    ON (CAT.CD_CATEGORIA = PROD.CD_CATEGORIA)
ORDER BY CAT.CD_CATEGORIA, PROD.DS_PRODUTO;

-- Resposta do Comando SQL item B)

SELECT  CLI.NR_CLIENTE,
        CLI.NM_CLIENTE,
        CLI.DS_EMAIL,
        CLI.NR_TELEFONE,
        CLI.NM_LOGIN,
        FIS.DT_NASCIMENTO,
        TO_CHAR(FIS.DT_NASCIMENTO, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS "DIA DA SEMANA NASCIMENTO",
        TRUNC(MONTHS_BETWEEN(SYSDATE, FIS.DT_NASCIMENTO)/12) AS "ANOS DE VIDA",
        FIS.FL_SEXO_BIOLOGICO,
        FIS.NR_CPF
    FROM MC_CLI_FISICA FIS INNER JOIN MC_CLIENTE CLI
        ON (CLI.NR_CLIENTE = FIS.NR_CLIENTE)

-- Resposta do Comando SQL item C)
        
SELECT  CLI.NR_CLIENTE,
        CLI.NM_CLIENTE,
        CLI.DS_EMAIL,
        CLI.NR_TELEFONE,
        CLI.NM_LOGIN,
        JUR.DT_FUNDACAO,
        TO_CHAR(JUR.DT_FUNDACAO, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS "DIA DA SEMANA FUNDAÇÃO",
        TRUNC(MONTHS_BETWEEN(SYSDATE, JUR.DT_FUNDACAO)/12) AS "ANOS DE VIDA DA EMPRESA",
        JUR.NR_CNPJ
    FROM MC_CLI_JURIDICA JUR INNER JOIN MC_CLIENTE CLI
        ON (CLI.NR_CLIENTE = JUR.NR_CLIENTE)

--Colocando a data em um cliente para que seja visível o cálculo de Idade e Dia da Semana

UPDATE MC_CLI_JURIDICA
    SET DT_FUNDACAO = TO_DATE ('02/02/1950', 'DD/MM/YYYY')
WHERE NR_CLIENTE = 12    

-- Resposta do Comando SQL item D)

SELECT  PROD.CD_PRODUTO, PROD.DS_PRODUTO, VIS.DT_VISUALIZACAO, VIS.NR_HORA_VISUALIZACAO
    FROM MC_SGV_VISUALIZACAO_VIDEO VIS INNER JOIN MC_PRODUTO PROD
    ON (PROD.CD_PRODUTO = VIS.CD_PRODUTO)
ORDER BY VIS.DT_VISUALIZACAO, VIS.NR_HORA_VISUALIZACAO



